name: happy_graduation_sayang
description: Web app hadiah wisuda Flutter
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ^3.24.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.0.0
  carousel_slider: ^5.1.1
  confetti: ^0.8.0
  url_launcher: ^6.2.0
  provider: ^6.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/data/memories.json
    - assets/images/
